export const FETCH_PRICES_REQUESTED = "FETCH_PRICES_REQUESTED";
export const FETCH_PRICES_SUCCESSED = "FETCH_PRICES_SUCCESSED";
export const FETCH_PRICES_FAILED = "FETCH_PRICES_FAILED";

export const CREATE_LINK_REQUESTED = "CREATE_LINK_REQUESTED";
export const CREATE_LINK_SUCCESSED = "CREATE_LINK_SUCCESSED";
export const CREATE_LINK_FAILED = "CREATE_LINK_FAILED";
